name: draftmode
description: Facade of all DraftMode flutter packages
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: "3.35.0"

# The facade depends on the real packages
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  draftmode_worker:
    path: ../worker
  draftmode_example:
    path: ../example
  draftmode_formatter:
    path: ../formatter
  draftmode_localization:
    path: ../localization
  draftmode_ui:
    path: ../ui

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true

repository: https://github.com/draftm0de/flutter
issue_tracker: https://github.com/draftm0de/flutter/issues
